export interface ICountry {
  id: number;
  name: string;
  code: number;
}
export const continentsAndCountries = [
  {
    name: 'Asia',
    countries: [
      { id: 1, name: 'Afghanistan', code: 'AF' },
      { id: 2, name: 'Armenia', code: 'AM' },
      { id: 3, name: 'Azerbaijan', code: 'AZ' },
      { id: 4, name: 'Bahrain', code: 'BH' },
      { id: 5, name: 'Bangladesh', code: 'BD' },
      { id: 6, name: 'Bhutan', code: 'BT' },
      { id: 7, name: 'Brunei', code: 'BN' },
      { id: 8, name: 'Cambodia', code: 'KH' },
      { id: 9, name: 'China', code: 'CN' },
      { id: 10, name: 'Cyprus', code: 'CY' },
      { id: 11, name: 'Georgia', code: 'GE' },
      { id: 12, name: 'India', code: 'IN' },
      { id: 13, name: 'Indonesia', code: 'ID' },
      { id: 14, name: 'Iran', code: 'IR' },
      { id: 15, name: 'Iraq', code: 'IQ' },
      { id: 16, name: 'Israel', code: 'IL' },
      { id: 17, name: 'Japan', code: 'JP' },
      { id: 18, name: 'Jordan', code: 'JO' },
      { id: 19, name: 'Kazakhstan', code: 'KZ' },
      { id: 20, name: 'Kuwait', code: 'KW' },
      { id: 21, name: 'Kyrgyzstan', code: 'KG' },
      { id: 22, name: 'Laos', code: 'LA' },
      { id: 23, name: 'Lebanon', code: 'LB' },
      { id: 24, name: 'Malaysia', code: 'MY' },
      { id: 25, name: 'Maldives', code: 'MV' },
      { id: 26, name: 'Mongolia', code: 'MN' },
      { id: 27, name: 'Myanmar', code: 'MM' },
      { id: 28, name: 'Nepal', code: 'NP' },
      { id: 29, name: 'North Korea', code: 'KP' },
      { id: 30, name: 'Oman', code: 'OM' },
      { id: 31, name: 'Pakistan', code: 'PK' },
      { id: 32, name: 'Palestine', code: 'PS' },
      { id: 33, name: 'Philippines', code: 'PH' },
      { id: 34, name: 'Qatar', code: 'QA' },
      { id: 35, name: 'Saudi Arabia', code: 'SA' },
      { id: 36, name: 'Singapore', code: 'SG' },
      { id: 37, name: 'South Korea', code: 'KR' },
      { id: 38, name: 'Sri Lanka', code: 'LK' },
      { id: 39, name: 'Syria', code: 'SY' },
      { id: 40, name: 'Tajikistan', code: 'TJ' },
      { id: 41, name: 'Thailand', code: 'TH' },
      { id: 42, name: 'Timor-Leste', code: 'TL' },
      { id: 43, name: 'Turkey', code: 'TR' },
      { id: 44, name: 'Turkmenistan', code: 'TM' },
      { id: 45, name: 'United Arab Emirates', code: 'AE' },
      { id: 46, name: 'Uzbekistan', code: 'UZ' },
      { id: 47, name: 'Vietnam', code: 'VN' },
      { id: 48, name: 'Yemen', code: 'YE' },
    ],
  },
  {
    name: 'Africa',
    countries: [
      { id: 1, name: 'Algeria', code: 'DZ' },
      { id: 2, name: 'Angola', code: 'AO' },
      { id: 3, name: 'Benin', code: 'BJ' },
      { id: 4, name: 'Botswana', code: 'BW' },
      { id: 5, name: 'Burkina Faso', code: 'BF' },
      { id: 6, name: 'Burundi', code: 'BI' },
      { id: 7, name: 'Cabo Verde', code: 'CV' },
      { id: 8, name: 'Cameroon', code: 'CM' },
      { id: 9, name: 'Central African Republic', code: 'CF' },
      { id: 10, name: 'Chad', code: 'TD' },
      { id: 11, name: 'Comoros', code: 'KM' },
      { id: 12, name: 'Congo', code: 'CG' },
      { id: 13, name: "Cote d'Ivoire", code: 'CI' },
      { id: 14, name: 'Djibouti', code: 'DJ' },
      { id: 15, name: 'Egypt', code: 'EG' },
      { id: 16, name: 'Equatorial Guinea', code: 'GQ' },
      { id: 17, name: 'Eritrea', code: 'ER' },
      { id: 18, name: 'Eswatini', code: 'SZ' },
      { id: 19, name: 'Ethiopia', code: 'ET' },
      { id: 20, name: 'Gabon', code: 'GA' },
      { id: 21, name: 'Gambia', code: 'GM' },
      { id: 22, name: 'Ghana', code: 'GH' },
      { id: 23, name: 'Guinea', code: 'GN' },
      { id: 24, name: 'Guinea-Bissau', code: 'GW' },
      { id: 25, name: 'Kenya', code: 'KE' },
      { id: 26, name: 'Lesotho', code: 'LS' },
      { id: 27, name: 'Liberia', code: 'LR' },
      { id: 28, name: 'Libya', code: 'LY' },
      { id: 29, name: 'Madagascar', code: 'MG' },
      { id: 30, name: 'Malawi', code: 'MW' },
      { id: 31, name: 'Mali', code: 'ML' },
      { id: 32, name: 'Mauritania', code: 'MR' },
      { id: 33, name: 'Mauritius', code: 'MU' },
      { id: 34, name: 'Morocco', code: 'MA' },
      { id: 35, name: 'Mozambique', code: 'MZ' },
      { id: 36, name: 'Namibia', code: 'NA' },
      { id: 37, name: 'Niger', code: 'NE' },
      { id: 38, name: 'Nigeria', code: 'NG' },
      { id: 39, name: 'Rwanda', code: 'RW' },
      { id: 40, name: 'Sao Tome and Principe', code: 'ST' },
      { id: 41, name: 'Senegal', code: 'SN' },
      { id: 42, name: 'Seychelles', code: 'SC' },
      { id: 43, name: 'Sierra Leone', code: 'SL' },
      { id: 44, name: 'Somalia', code: 'SO' },
      { id: 45, name: 'South Africa', code: 'ZA' },
      { id: 46, name: 'South Sudan', code: 'SS' },
      { id: 47, name: 'Sudan', code: 'SD' },
      { id: 48, name: 'Tanzania', code: 'TZ' },
      { id: 49, name: 'Togo', code: 'TG' },
      { id: 50, name: 'Tunisia', code: 'TN' },
      { id: 51, name: 'Uganda', code: 'UG' },
      { id: 52, name: 'Zambia', code: 'ZM' },
      { id: 53, name: 'Zimbabwe', code: 'ZW' },
    ],
  },
  {
    name: 'Europe',
    countries: [
      { id: 1, name: 'Albania', code: 'AL' },
      { id: 2, name: 'Andorra', code: 'AD' },
      { id: 3, name: 'Austria', code: 'AT' },
      { id: 4, name: 'Belarus', code: 'BY' },
      { id: 5, name: 'Belgium', code: 'BE' },
      { id: 6, name: 'Bosnia and Herzegovina', code: 'BA' },
      { id: 7, name: 'Bulgaria', code: 'BG' },
      { id: 8, name: 'Croatia', code: 'HR' },
      { id: 9, name: 'Cyprus', code: 'CY' },
      { id: 10, name: 'Czech Republic', code: 'CZ' },
      { id: 11, name: 'Denmark', code: 'DK' },
      { id: 12, name: 'Estonia', code: 'EE' },
      { id: 13, name: 'Finland', code: 'FI' },
      { id: 14, name: 'France', code: 'FR' },
      { id: 15, name: 'Germany', code: 'DE' },
      { id: 16, name: 'Greece', code: 'GR' },
      { id: 17, name: 'Hungary', code: 'HU' },
      { id: 18, name: 'Iceland', code: 'IS' },
      { id: 19, name: 'Ireland', code: 'IE' },
      { id: 20, name: 'Italy', code: 'IT' },
      { id: 21, name: 'Kosovo', code: 'XK' },
      { id: 22, name: 'Latvia', code: 'LV' },
      { id: 23, name: 'Liechtenstein', code: 'LI' },
      { id: 24, name: 'Lithuania', code: 'LT' },
      { id: 25, name: 'Luxembourg', code: 'LU' },
      { id: 26, name: 'Malta', code: 'MT' },
      { id: 27, name: 'Moldova', code: 'MD' },
      { id: 28, name: 'Monaco', code: 'MC' },
      { id: 29, name: 'Montenegro', code: 'ME' },
      { id: 30, name: 'Netherlands', code: 'NL' },
      { id: 31, name: 'North Macedonia', code: 'MK' },
      { id: 32, name: 'Norway', code: 'NO' },
      { id: 33, name: 'Poland', code: 'PL' },
      { id: 34, name: 'Portugal', code: 'PT' },
      { id: 35, name: 'Romania', code: 'RO' },
      { id: 36, name: 'Russia', code: 'RU' },
      { id: 37, name: 'San Marino', code: 'SM' },
      { id: 38, name: 'Serbia', code: 'RS' },
      { id: 39, name: 'Slovakia', code: 'SK' },
      { id: 40, name: 'Slovenia', code: 'SI' },
      { id: 41, name: 'Spain', code: 'ES' },
      { id: 42, name: 'Sweden', code: 'SE' },
      { id: 43, name: 'Switzerland', code: 'CH' },
      { id: 44, name: 'Ukraine', code: 'UA' },
      { id: 45, name: 'United Kingdom', code: 'GB' },
      { id: 46, name: 'Vatican City', code: 'VA' },
    ],
  },
];
